disable_env_checking: True
framework: torch
num_gpus: 0.1
num_workers: 16
num_envs_per_worker: 5
# horizon: 1000
horizon: null
clip_rewards: True
evaluation_num_workers: 16
evaluation_interval: 10
evaluation_duration: 320
evaluation_config:
    # num_gpus_per_worker: 0.01
    num_envs_per_worker: 1
    explore: False

rollout_fragment_length: 50
train_batch_size: 500
num_multi_gpu_tower_stacks: 4
lr_schedule: [[0, 0.0005], [50000000, 0.000000000001]]
min_time_s_per_reporting: null # to disable original setting
timesteps_per_iteration: 500000
log_level: DEBUG

env: BreakoutNoFrameskip-v4

model:
    post_fcnet_hiddens: [256,128,64]
    custom_model: "MyVisonNetwork"